import {it,expect} from 'vitest'
import {mkdtemp,readFile,writeFile,stat,rm} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {createHash} from 'node:crypto'
import {ModelManager} from '../electron/main/character-chat/ModelManager'
import {CHAT_MODELS} from '../electron/main/character-chat/catalog'
const bytes=Buffer.from('official-model-fixture');const model={...CHAT_MODELS.E4B,filename:'fixture.gguf',bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};const catalog={E4B:model,'12B':{...model,filename:'other.gguf'}};
it('resumes a partial file and atomically exposes only the verified model',async()=>{const root=await mkdtemp(join(tmpdir(),'chat-download-'));try{await writeFile(join(root,model.filename+'.partial'),bytes.subarray(0,5));const requests:RequestInit[]=[];const manager=new ModelManager(root,()=>{},{catalog,fetch:async(_url,init)=>{requests.push(init!);return new Response(bytes.subarray(5),{status:206,headers:{'content-range':`bytes 5-${bytes.length-1}/${bytes.length}`}})}});await manager.download('E4B');expect(requests[0].headers).toEqual({Range:'bytes=5-'});expect(await manager.verify('E4B')).toBe(join(root,model.filename));expect(await readFile(manager.path('E4B'))).toEqual(bytes);expect(await manager.installed()).toEqual(['E4B'])}finally{await rm(root,{recursive:true,force:true})}})
it('hash failure preserves the previously installed model and does not use a corrupt partial',async()=>{const root=await mkdtemp(join(tmpdir(),'chat-hash-'));try{await writeFile(join(root,model.filename),bytes);const manager=new ModelManager(root,()=>{},{catalog,fetch:async()=>new Response(Buffer.alloc(bytes.length,1))});await expect(manager.download('E4B')).rejects.toThrow('검증');expect(await readFile(manager.path('E4B'))).toEqual(bytes);await expect(stat(manager.path('E4B')+'.partial')).rejects.toThrow()}finally{await rm(root,{recursive:true,force:true})}})
it('disk space failure happens before network access; local import rejects the wrong model',async()=>{const root=await mkdtemp(join(tmpdir(),'chat-space-'));try{let calls=0;const manager=new ModelManager(root,()=>{},{catalog,freeBytes:async()=>0,fetch:async()=>{calls++;return new Response(bytes)}});await expect(manager.download('E4B')).rejects.toThrow('공간');expect(calls).toBe(0);const wrong=join(root,'wrong');await writeFile(wrong,'wrong');const local=new ModelManager(root,()=>{},{catalog});await expect(local.importFile('E4B',wrong)).rejects.toThrow('공식 GGUF');expect(await local.installed()).toEqual([])}finally{await rm(root,{recursive:true,force:true})}})
it('cancellation actually aborts the transfer and leaves a resumable prefix',async()=>{const root=await mkdtemp(join(tmpdir(),'chat-cancel-'));try{let manager:ModelManager;manager=new ModelManager(root,p=>{if(p?.bytes===5)setTimeout(()=>void manager.cancel(),0)},{catalog,fetch:async(_url,init)=>new Response(new ReadableStream({start(controller){controller.enqueue(bytes.subarray(0,5));init?.signal?.addEventListener('abort',()=>controller.error(new DOMException('cancelled','AbortError')),{once:true})}}))});await expect(manager.download('E4B')).rejects.toThrow();expect(await readFile(manager.path('E4B')+'.partial')).toEqual(bytes.subarray(0,5));expect(await manager.installed()).toEqual([])}finally{await rm(root,{recursive:true,force:true})}})
