import {describe,it,expect} from 'vitest'
import {validateChatDefinition,resolveChatPose,neutralMeaning,parseChatReply,emptyChat} from '../electron/shared/character-chat-semantics'
import {dialoguePrefix,ChatSSEDecoder} from '../electron/shared/character-chat-stream'
import {completeContext,ConversationStore,validateStoredChats} from '../electron/main/character-chat/ConversationStore'
import {compileChatAuthoring} from '../scripts/characters/chat-authoring.mjs'
import {mkdtemp,rm,readFile,writeFile,readdir} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {randomUUID} from 'node:crypto'
const rule=(id:string,poseId:string,when:Record<string,string>,extra={})=>({id,poseId,when,motionPolicy:'chat-safe',priority:0,weight:1,...extra})
const meaning=(emotion='neutral',intent='chat',intensity=.3)=>({...neutralMeaning(),emotion,intent,intensity}) as ReturnType<typeof neutralMeaning>
describe('pack-declared character chat semantics',()=>{
 it('resolves the same meaning with wholly different pose IDs and no global mapping',()=>{for(const ids of [['pose_07','pose_42'],['chin_rest','quiet_palms']]){const d=validateChatDefinition({schemaVersion:1,presentation:{rules:[rule('prep',ids[0],{phase:'generating'}),rule('comfort',ids[1],{phase:'replying',emotion:'concerned'})]}},ids,true).value;expect(resolveChatPose(d,'generating').poseId).toBe(ids[0]);expect(resolveChatPose(d,'replying',meaning('concerned')).poseId).toBe(ids[1])}})
 it('AND conditions and emotion fallback never choose neutral explanation for concern',()=>{const d=validateChatDefinition({schemaVersion:1,presentation:{rules:[rule('explain','p1',{phase:'replying',intent:'explain'}),rule('joy','p2',{phase:'replying',emotion:'happy',intent:'celebrate'})]}},['p1','p2'],true).value;expect(resolveChatPose(d,'replying',meaning('concerned','explain')).poseId).toBeNull();expect(resolveChatPose(d,'replying',meaning('neutral','explain')).poseId).toBe('p1');expect(resolveChatPose(d,'replying',meaning('happy','chat')).poseId).toBeNull()})
 it('does not invent a base pose ID for a legacy pack',()=>expect(resolveChatPose(emptyChat(),'idle').poseId).toBeNull())
 it('intensity boundaries, rank, priority and nonrepeat weighted variants',()=>{const rules=[rule('low','small',{phase:'replying',emotion:'happy'},{intensity:{min:0,max:.64}}),rule('high','large',{phase:'replying',emotion:'happy',intent:'celebrate'},{intensity:{min:.65,max:1}}),rule('alt','other',{phase:'replying',emotion:'happy',intent:'celebrate'},{intensity:{min:.65,max:1}})];const d=validateChatDefinition({schemaVersion:1,presentation:{rules}},['small','large','other'],true).value;expect(resolveChatPose(d,'replying',meaning('happy','celebrate',.64)).poseId).toBe('small');expect(resolveChatPose(d,'replying',meaning('happy','celebrate',.65),'large',()=>0).poseId).toBe('other')})
 it.each([{poseId:'../../evil'},{weight:NaN},{weight:Infinity},{weight:0},{intensity:{min:.8,max:.1}},{when:{phase:'generating',emotion:'happy'}},{when:{phase:'replying',emotion:'thinking'}},{code:'execute()'}])('rejects unsafe rule %j and degrades only optional semantics',patch=>{const v={schemaVersion:1,presentation:{rules:[{...rule('r','arbitrary',{phase:'replying'}),...patch}]}};expect(()=>validateChatDefinition(v,['arbitrary'],true)).toThrow();expect(validateChatDefinition(v,['arbitrary']).value.presentation.rules).toHaveLength(0)})
 it('rejects duplicate IDs and unsupported documents with diagnostics',()=>{const r=rule('same','x',{phase:'idle'});expect(()=>validateChatDefinition({schemaVersion:1,presentation:{rules:[r,r]}},['x'],true)).toThrow();expect(validateChatDefinition({schemaVersion:8},[]).diagnostics).toContain('CHAT_VERSION')})
 it('creator exports only confirmed intent, preserves overrides and is idempotent',()=>{const tools={validateChatDefinition,emptyChat};const plan={models:[{id:'arbitrary',meaningReview:'confirmed',intendedMeaning:{when:{phase:'generating'}}},{id:'happy-name-only'},{id:'uncertain',meaningReview:'needs-review',intendedMeaning:{when:{phase:'replying',emotion:'happy'}}}]};const ids=plan.models.map(x=>x.id),a=compileChatAuthoring(tools,plan,ids);expect(a.chat.presentation.rules).toHaveLength(1);expect(a.report.map((r:any)=>r.status)).toEqual(['confirmed','unmapped','needs-review']);const b=compileChatAuthoring(tools,plan,ids,a.chat);expect(b.chat).toEqual(a.chat)})
})
describe('single-pass structured dialogue streaming',()=>{
 it('text extraction works at every byte boundary and ignores JSON keys',()=>{const raw=JSON.stringify({emotion:'happy',gesture:'nod',intent:'chat',intensity:.3,text:'안녕. "함께" 이야기해요. 😀\n다음 줄'});const expected=JSON.parse(raw).text;for(let i=0;i<=raw.length;i++){const value=dialoguePrefix(raw.slice(0,i));expect(expected.startsWith(value)).toBe(true);expect(value).not.toContain('emotion')}expect(dialoguePrefix(raw)).toBe(expected)})
 it('split Unicode escapes never expose partial surrogate or slash',()=>{expect(dialoguePrefix('{"text":"\\uD83D')).toBe('');expect(dialoguePrefix('{"text":"\\uD83D\\uDE00')).toBe('😀');expect(dialoguePrefix('{"intent":"chat","text":"한글\\')).toBe('한글')})
 it('reordered text validates without accepting phase, pose ID or invalid intensity',()=>{expect(parseChatReply('{"intensity":0.2,"text":"안녕하세요","gesture":"none","intent":"chat","emotion":"neutral"}').text).toBe('안녕하세요');expect(()=>parseChatReply('{"text":"hi","intensity":2,"gesture":"none","intent":"chat","emotion":"neutral"}')).toThrow();expect(()=>parseChatReply('{"text":"hi","phase":"idle"}')).toThrow()})
 it('SSE handles UTF8 boundaries, empty metadata and CRLF without chunk token guesses',()=>{const events:string[]=[];const parser=new ChatSSEDecoder(s=>events.push(s));for(const byte of Buffer.from('data: {"text":"한글"}\r\n\r\ndata: [DONE]\n\n'))parser.push(Uint8Array.of(byte));parser.end();expect(events).toEqual(['{"text":"한글"}','[DONE]'])})
})
describe('local conversation storage and history',()=>{
 const msg=(role:'user'|'assistant',text:string,status:'complete'|'stopped'='complete')=>({id:randomUUID(),role,text,status,createdAt:new Date().toISOString()});
 it('does not put aborted answers or orphan users in later context',()=>{const history=[msg('user','old'),msg('assistant','partial','stopped'),msg('user','valid'),msg('assistant','reply'),msg('user','new')];expect(completeContext(history)).toEqual([{role:'user',content:'valid'},{role:'assistant',content:'reply'},{role:'user',content:'new'}])})
 it('round trips characters, explicit memories and summaries; protects corrupt source',async()=>{const root=await mkdtemp(join(tmpdir(),'local-chat-store-'));try{const store=new ConversationStore(root),id=randomUUID();const data={version:2 as const,model:'E4B' as const,characterId:'synthetic-a',current:id,conversations:[{id,characterId:'synthetic-a',title:'saved',messages:[msg('user','hello'),msg('assistant','hi')],updatedAt:new Date().toISOString(),summary:{text:'user excerpt',algorithm:'extractive-v1' as const}}],memories:{'synthetic-a':[{id:randomUUID(),text:'explicit'}]}};await store.save(data);expect((await new ConversationStore(root).load()).value).toEqual(data);await writeFile(store.file,'broken');expect((await store.load()).recovered).toBe(true);const backup=(await readdir(root)).find(p=>p.includes('.preserved-'));expect(await readFile(join(root,backup!),'utf8')).toBe('broken')}finally{await rm(root,{recursive:true,force:true})}})
 it('invalid storage does not silently become trusted conversation state',()=>expect(()=>validateStoredChats({version:2,model:'E4B',characterId:'x',conversations:[{id:'../bad'}]})).toThrow())
})

it('presentation is epoch/pack bound; fast responses cancel thinking and old motion',async()=>{
 const {vi}=await import('vitest');vi.useFakeTimers();try{const {ChatPresentationController}=await import('../src/character-chat/ChatPresentationController');const runtime={cancelPendingPoseLoad:vi.fn(),setChatMotionPolicy:vi.fn(),getPoseDiagnostics:()=>({id:null}),transitionToPose:vi.fn(async(..._args:unknown[])=>{}),exitPose:vi.fn(async()=>{}),resetPose:vi.fn(),getBaseFaceGeometry:()=>null};const session={runtime,behavior:{setControlMode:vi.fn(),setPresentationSuspended:vi.fn()},setInteractionEnabled:vi.fn(),dialogue:{setEnabled:vi.fn(),clear:vi.fn()}};const controller=new ChatPresentationController(session as any),definition=validateChatDefinition({schemaVersion:1,presentation:{rules:[rule('prepare','arbitrary',{phase:'generating'}),rule('joy','other',{phase:'replying',emotion:'happy'})]}},['arbitrary','other'],true).value;
 const p={active:true,epoch:1,characterId:'synthetic-a',revision:'revision',phase:'generating' as const,definition,meaning:null};controller.update(p,'synthetic-a','revision');controller.update({...p,phase:'idle',meaning:meaning('happy')},'synthetic-a','revision');await vi.advanceTimersByTimeAsync(500);expect(runtime.transitionToPose).toHaveBeenCalledTimes(1);expect(runtime.transitionToPose.mock.calls[0][0]).toBe('other');controller.update({...p,epoch:0},'synthetic-a','revision');await vi.advanceTimersByTimeAsync(500);expect(runtime.transitionToPose).toHaveBeenCalledTimes(1);controller.update({...p,epoch:2,characterId:'other'},'synthetic-a','revision');expect(session.behavior.setControlMode).toHaveBeenLastCalledWith('AUTO_BEHAVIOR');controller.dispose()}finally{vi.useRealTimers()}
})

it('validates display names and preserves existing profile and pose rules on name-only authoring', () => {
 const previous=emptyChat();previous.profile.canonFacts=['preserved fact'];
 const tools={validateChatDefinition,emptyChat};
 const updated=compileChatAuthoring(tools,{profile:{displayName:'  별이  '}},[],previous).chat;
 expect(updated.profile.displayName).toBe('별이');
 expect(updated.profile.canonFacts).toEqual(['preserved fact']);
 for(const displayName of ['', 'x'.repeat(81), 'bad\u202ename'])expect(()=>validateChatDefinition({schemaVersion:1,profile:{displayName}},[],true)).toThrow();
 expect(emptyChat().profile.displayName).toBeUndefined();
})
