import { it, expect, vi } from "vitest"
import { mkdtemp, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { UpdateService } from "../electron/main/updates/UpdateService"
import { BUNDLE_ID } from "../electron/shared/app-identity.mjs"
const info = { version: "0.7.3", tag: "v0.7.3", path: "Daemonlet-for-Codex-0.7.3-macOS-arm64.zip", sha512: Buffer.alloc(64, 1).toString("base64"), files: [{ url: "Daemonlet-for-Codex-0.7.3-macOS-arm64.zip", size: 1234567, sha512: Buffer.alloc(64, 1).toString("base64") }], minimumSystemVersion: "22.0.0", daemonlet: { appId: BUNDLE_ID, platform: "darwin", arch: "arm64", installType: "mac" } }
async function withService(test: (ctx: any) => Promise<void>) {
  const dataRoot = await mkdtemp(join(tmpdir(), "daemonlet-updates-"))
  const engine = { check: vi.fn(async () => info), download: vi.fn(async () => {}), verify: vi.fn(async () => {}), prepare: vi.fn(async () => {}), install: vi.fn() }
  const options = { version: "0.7.2", platform: vi.fn(async () => ({ platform: "darwin", arch: "arm64", osVersion: "26.0.0", kind: "mac" as const, automatic: true })), engine: () => engine, dataRoot, autoCheck: vi.fn(() => false), confirmInstall: vi.fn(async () => true), prepareShutdown: vi.fn(async () => {}), handoff: vi.fn(), resume: vi.fn(), openExternal: vi.fn(async () => {}), now: () => 100000 }
  const service = new UpdateService(options)
  try { await test({ engine, options, service }) } finally { service.dispose(); await rm(dataRoot, { recursive: true, force: true }) }
}
it("does not make startup requests when automatic checks are OFF", () => withService(async ({ engine, service }) => { await service.start(); expect(engine.check).not.toHaveBeenCalled() }))
it("never downloads during a manual metadata check", () => withService(async ({ engine, service }) => { await service.act({ action: "check" }); expect(service.snapshot().phase).toBe("available"); expect(engine.download).not.toHaveBeenCalled(); expect(engine.prepare).not.toHaveBeenCalled() }))
it("ignores stale IDs and separates download from staging/restart", () => withService(async ({ engine, service }) => { await service.act({ action: "check" }); await service.act({ action: "download", candidateId: "stale" }); expect(engine.download).not.toHaveBeenCalled(); await service.act({ action: "download", candidateId: service.snapshot().candidateId }); expect(service.snapshot().phase).toBe("downloaded"); expect(engine.prepare).not.toHaveBeenCalled(); expect(engine.install).not.toHaveBeenCalled() }))
it("consent cancellation preserves child, draft and windows without preparation", () => withService(async ({ engine, options, service }) => { await service.act({ action: "check" }); const candidateId = service.snapshot().candidateId; await service.act({ action: "download", candidateId }); options.confirmInstall.mockResolvedValue(false); await service.act({ action: "installAndRestart", candidateId }); expect(service.snapshot().phase).toBe("downloaded"); expect(options.prepareShutdown).not.toHaveBeenCalled(); expect(engine.prepare).not.toHaveBeenCalled() }))
it("verifies and stages before owned cleanup, then hands off without app.exit", () => withService(async ({ engine, options, service }) => { const order: string[] = []; for (const key of ["verify", "prepare", "install"]) engine[key].mockImplementation(async () => { order.push(key) }); options.prepareShutdown.mockImplementation(async () => { order.push("cleanup") }); options.handoff.mockImplementation(() => { order.push("handoff") }); await service.act({ action: "check" }); const candidateId = service.snapshot().candidateId; await service.act({ action: "download", candidateId }); await service.act({ action: "installAndRestart", candidateId }); expect(order).toEqual(["verify", "prepare", "cleanup", "handoff", "install"]) }))
it("cleanup or signature failure cannot launch installer", () => withService(async ({ engine, options, service }) => { await service.act({ action: "check" }); const candidateId = service.snapshot().candidateId; await service.act({ action: "download", candidateId }); options.prepareShutdown.mockRejectedValue(Error("SAVE_FAILED")); await service.act({ action: "installAndRestart", candidateId }); expect(engine.install).not.toHaveBeenCalled(); expect(options.resume).toHaveBeenCalled(); expect(service.snapshot().reason).toBe("SAVE_FAILED") }))
it("cancels a slow download and rejects its late success", () => withService(async ({ engine, service }) => { let finish!: () => void; engine.download.mockImplementation(() => new Promise<void>(r => { finish = r })); await service.act({ action: "check" }); const pending = service.act({ action: "download", candidateId: service.snapshot().candidateId }); await Promise.resolve(); await service.act({ action: "cancelDownload" }); finish(); await pending; expect(service.snapshot().phase).toBe("available"); expect(engine.prepare).not.toHaveBeenCalled() }))
it("unsigned and portable installs never enter automatic download", () => withService(async ({ engine, options, service }) => { options.platform.mockResolvedValue({ platform: "darwin", arch: "arm64", osVersion: "26.0.0", kind: "mac", automatic: false, reason: "MAC_INSTALL_OR_TRUST" }); await service.act({ action: "check" }); expect(service.snapshot().phase).toBe("manualOnly"); await service.act({ action: "download", candidateId: service.snapshot().candidateId }); expect(engine.download).not.toHaveBeenCalled() }))
it("backs off background checks and rate limits repeated manual checks", () => withService(async ({ engine, options, service }) => { options.autoCheck.mockReturnValue(true); await service.check(true); await service.check(true); expect(engine.check).toHaveBeenCalledTimes(1); await service.check(false); await service.check(false); expect(engine.check).toHaveBeenCalledTimes(2) }))
it("does not install after OS shutdown while consent is pending", () => withService(async ({ engine, options, service }) => { let finish!: (yes: boolean) => void; options.confirmInstall.mockImplementation(() => new Promise(r => { finish = r })); await service.act({ action: "check" }); const candidateId = service.snapshot().candidateId; await service.act({ action: "download", candidateId }); const pending = service.act({ action: "installAndRestart", candidateId }); service.dispose(); finish(true); await pending; expect(engine.prepare).not.toHaveBeenCalled(); expect(engine.install).not.toHaveBeenCalled() }))
