import type { SetupConfigurationStatus } from "../../electron/shared/codex-integration-contract"

export const configurationLabels: Record<SetupConfigurationStatus, string> = {
  "not-installed": "아직 설치되지 않음", "installed-current": "현재 앱의 Hook 설치됨",
  "installed-legacy": "개발 경로의 Hook 감지", "partially-installed": "일부 Hook만 설치됨",
  "repair-needed": "Hook 수리 필요", "configuration-conflict": "설정 충돌 확인 필요",
  "feature-disabled": "Codex Hook 기능 꺼짐", "policy-blocked": "관리자 정책으로 차단됨",
  "capability-unknown": "지원 계약 확인 필요", "host-unavailable": "Hook 실행 호스트 확인 필요",
}

const reasons: Record<string, string> = {
  HOST_UNAVAILABLE: "동봉 실행 파일을 사용할 수 없습니다. 앱의 실행 파일과 resource를 확인해 주세요.",
  HOST_SELF_TEST_REQUIRED: "이 앱 버전으로 동봉 Hook 검사를 먼저 실행해 주세요.",
  PACKAGED_APP_REQUIRED: "설치된 Daemonlet 앱에서 설정해 주세요.",
  PACKAGED_MAC_REQUIRED: "설치된 macOS 앱에서 연결을 설정해 주세요. 개발 실행은 패키지 설치 검증에 해당하지 않습니다.",
  PERMANENT_APP_LOCATION_REQUIRED: "현재 앱이 임시·빌드 위치에 있습니다. 사용할 영구 위치로 앱을 옮긴 뒤 다시 실행해 주세요.",
  PACKAGED_TIMEOUT_2_SECONDS: "패키지 첫 실행 측정에 따라 Hook timeout을 2초로 설정합니다. 동봉 forwarder의 처리 시간 제한은 유지됩니다.",
  HOOK_FEATURE_DISABLED: "선택한 Codex에서 Hook 기능이 꺼져 있습니다. 아래 안내에 따라 직접 활성화해 주세요.",
  HOOK_FEATURE_UNKNOWN: "선택한 Codex의 Hook 활성 상태를 확인하지 못했습니다.",
  MANAGED_POLICY_BLOCKED: "관리자 정책이 사용자 Hook 실행을 차단합니다. 관리자에게 확인해 주세요.",
  CAPABILITY_CONTRACT_UNKNOWN: "이 Codex 바이너리에 대해 검증된 Hook 계약이 없습니다. 버전 번호만으로 설치를 허용하지 않습니다.",
  CORE_EVENTS_UNCONFIRMED: "작업 시작·완료 이벤트의 지원이 확인되지 않아 설치를 보류합니다.",
  EXISTING_EVENT_UNCONFIRMED: "기존 Hook 중 지원이 미확인인 이벤트가 있습니다. 기존 항목을 보존하고 자동 변경을 보류합니다.",
  EXISTING_UNCONFIRMED_EVENTS_PRESERVED: "미확인 이벤트의 기존 앱 Hook을 보존합니다.",
  INLINE_OWNED_HOOK_CONFLICT: "config.toml에도 이 앱의 Hook으로 의심되는 항목이 있습니다. 중복 설치를 막기 위해 직접 확인이 필요합니다.",
  CONFIG_UNREADABLE_OR_INVALID: "설정 파일을 안전하게 읽거나 해석하지 못했습니다. 원본은 유지됩니다.",
  ADAPTER_STATE_UNCONFIRMED: "현재 Adapter의 작업 상태를 확인할 수 없습니다. 외부 Adapter는 이 앱에서 종료하거나 교체하지 않습니다.",
  ACTIVE_RUN: "진행 중인 Codex 작업이 있습니다. 작업이 끝난 뒤 다시 미리보기를 만들어 주세요.",
  AMBIGUOUS_HANDLER: "앱 Hook과 비슷하지만 command·옵션·matcher가 다릅니다. 자동 제거하지 않고 확인을 요청합니다.",
  REPLACE_PREVIOUS_COMMAND: "이전 앱 command를 교체", REMOVE_DUPLICATE: "중복 앱 handler 정리",
  CURRENT_APP_COMMAND: "현재 앱의 동봉 Hook 추가", REMOVE_OWNED_HANDLER: "이 앱의 handler만 제거",
  REVERT_OWNED_CHANGE: "마지막 앱 변경을 역적용", RESTORE_PREVIOUS_OWNED_HANDLER: "이전 앱 handler 복원",
  JSON_WHITESPACE_MAY_CHANGE: "JSON의 들여쓰기와 공백 형식이 바뀔 수 있습니다. 다른 handler의 내용·순서·metadata는 보존합니다.",
  HOOK_REVIEW_REQUIRED: "변경 뒤 Codex에서 정확한 Hook 정의를 다시 검토·신뢰해야 할 수 있습니다.",
  PLAN_STALE: "미리보기 이후 설정·앱·대상이 바뀌었습니다. 최신 상태로 미리보기를 다시 만들어 주세요.",
  PLAN_EXPIRED: "미리보기가 만료되었습니다. 새 미리보기를 만들어 주세요.",
  PLAN_UNKNOWN: "사용할 수 없는 미리보기입니다. 새 미리보기를 만들어 주세요.",
  PLAN_SUPERSEDED: "더 최근의 미리보기가 있습니다. 최신 변경 내용을 확인해 주세요.",
  PLAN_BLOCKED: "아래 확인이 필요한 항목을 해결한 뒤 새 미리보기를 만들어 주세요.",
  TARGET_BUSY: "다른 앱 복사본이 이 설정을 변경 중이거나 설치 잠금을 남겼습니다. 해당 작업을 확인해 주세요.",
  TARGET_NOT_WRITABLE: "hooks.json이 읽기 전용입니다. 파일 권한을 직접 확인해 주세요.",
  UNSAFE_FILE: "symlink·파일 소유자·권한을 확인할 수 없어 변경을 보류했습니다.",
  UNSAFE_CODEX_HOME: "선택한 Codex Home의 소유자 또는 쓰기 권한을 확인해 주세요.",
  SYMLINK_CODEX_HOME: "symlink 대신 실제 Codex Home 폴더를 선택해 주세요.",
  FILE_TOO_LARGE: "설정 파일이 1 MiB 한도를 넘어 변경을 보류했습니다.",
  RESULT_TOO_LARGE: "변경 후 설정이 1 MiB 한도를 넘게 되어 적용을 보류했습니다.",
  PLAN_TOO_COMPLEX: "한 번에 확인할 앱 변경이 너무 많습니다. 기존 설정을 보존하고 자동 적용을 보류했습니다.",
  INVALID_HOOK_CONFIGURATION: "hooks.json이 잘못되었거나 중복 key가 있습니다. 원본 파일을 직접 확인해 주세요.",
  RECEIPT_RECOVERY_REQUIRED: "이전 설치 기록과 현재 상태를 확인해야 합니다. 자동 복원하지 않습니다. 진단 탭의 보호된 설치 기록 위치를 확인해 주세요.",
  COMMITTED_RECEIPT_RECOVERED: "이전 실행의 미완료 기록을 발견했습니다. 현재 파일이 적용 후 내용과 일치함을 확인했습니다. 원본을 덮어쓰지 않았습니다.",
  PREPARED_CHANGE_NOT_COMMITTED: "이전 시도의 변경이 적용되지 않은 것으로 확인했습니다. 현재 파일을 보존하고, 새 미리보기와 승인을 통해 다시 진행합니다.",
  ABORT_RECEIPT_WRITE_FAILED: "설정 교체 전에 중단했지만 중단 기록을 안전하게 저장하지 못했습니다. 보호된 설치 기록과 현재 파일을 다시 확인해야 합니다.",
  COMMIT_OUTCOME_UNKNOWN: "설정 교체 결과를 확정하지 못했습니다. 설치 기록과 현재 파일을 다시 확인해야 하며, 자동 복원하지 않습니다.",
  NO_REVERSIBLE_RECEIPT: "되돌릴 앱 변경 기록이 없습니다.",
  OWNED_CHANGE_DIVERGED: "앱 Hook이 이후에 변경되어 자동으로 되돌릴 수 없습니다. 현재 설정을 보존합니다.",
  REVERT_GROUP_DIVERGED: "이전 앱 handler를 복원할 group을 확정할 수 없습니다. 현재 설정을 보존합니다.",
  CLI_NOT_FOUND_DESKTOP_MAY_STILL_WORK: "CLI를 찾지 못했습니다. Desktop만 사용하는 환경일 수 있으며, 앱 실행 실패를 의미하지 않습니다.",
  SELECT_EXECUTABLE_BEFORE_PROBE: "발견한 실행 파일의 자동 실행을 보류했습니다. 사용할 Codex 실행 파일을 직접 선택해 주세요.",
  SELECTED_CODEX_UNAVAILABLE: "선택된 Codex 실행 파일에 접근할 수 없습니다. 대상을 다시 선택해 주세요.",
  CODEX_PROBE_FAILED: "Codex의 읽기 전용 버전·feature 검사가 완료되지 않았습니다.",
  OPERATION_IN_PROGRESS: "현재 작업이 끝난 뒤 다시 시도해 주세요.",
  REQUEST_LIMITED: "요청이 많아 잠시 제한했습니다. 잠시 후 다시 시도해 주세요.",
  OWNED_ADAPTER_REQUIRED: "이 앱이 실행한 Adapter가 준비된 뒤 관찰할 수 있습니다.",
  NO_HOOKS_TO_REVIEW: "설치된 앱 Hook을 먼저 확인해 주세요.",
  INTEGRATION_STORE_UNREADABLE: "앱의 연결 설정 파일을 읽지 못했습니다. 기존 파일을 보존했습니다.",
  INTEGRATION_STORE_CHANGED: "다른 앱에서 연결 설정을 변경했습니다. 앱을 다시 열어 최신 상태를 확인해 주세요.",
  ENOSPC: "저장 공간이 부족해 변경하지 못했습니다. 공간을 확보한 뒤 다시 시도해 주세요.",
}
export function reasonText(code: string): string { return PACK_ERRORS[code] ?? reasons[code.split(":")[0]] ?? "작업을 완료하지 못했습니다. 상태를 새로 확인하고 다시 시도해 주세요." }
export const supportLabels = { supported: "지원 확인", unsupported: "미지원", unknown: "미확인" } as const
import { PACK_ERRORS } from "../../electron/shared/character-pack-contract"
